services:
  retire:
    build: { context: ., dockerfile: Dockerfile }
    command: sleep infinity
    environment:
      XGEM_HOME: /workspaces/retire/vendor/bundle/ruby
      ELASTICSEARCH_URL: http://customink-elasticsearch64:9200
    privileged: true
    user: vscode
    depends_on:
      customink-elasticsearch64: { condition: service_started }

  customink-elasticsearch64:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.16"
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      [
        "/var/lib/docker/codespacemount/data-elasticsearch:/usr/share/elasticsearch/data",
      ]


networks:
  default: { ipam: { config: [{ subnet: 192.168.176.0/24 }] } }